### ISSUE TITLE
Contract compilation error

### ISSUE THREAD

**Issue by iammprashant** [prnvbaraiya/E-Voting-System-Using-Blockchain#3]
Hello,

There is compilation error while compiling the Transaction.sol .
![image](https://user-images.githubusercontent.com/92540295/232374707-3093f8d0-21d5-4992-97b8-f7c4a3984642.png)

**Comment by prnvbaraiya** [comment]
Hello Prashant,

Thank you for bringing this to my attention. It seems like the problem might be due to an empty Transaction.json file in the build folder.It could be resolved by deleting the file and re-compiling. Please try deleting the Transaction.json file from smart_contract/build and re-compile the code. Hopefully, this should resolve the issue.

Let me know if you face any further problems.
